### ISSUE TITLE
Initailize B3log Solo error: The API call datastore_v3.Get() required more quota than is available.

### ISSUE THREAD

**Issue by zhulinke** [b3log/b3log-solo#11991]
![issue](https://cloud.githubusercontent.com/assets/4800553/5689592/0e127876-981d-11e4-9fc7-51937aefbe53.png)

1月2日我成功搭载完毕，一切正常
到昨天晚上还可以访问，
但今天早上突然出现初始化的页面，
我刷新了几遍，还是这样，
后来我就填写表格初始化，就出现以下页面。
PS: GAE

**Comment by 88250** [comment]
GAE 的配额是每天计算的，如果配额用超了就会出现这样的情况。（配额大概是每天下午 4 点左右重置）

----

建议不要使用 GAE 了，毕竟：
> 天下没有免费的午餐

如果觉得自己搭建 VPS 麻烦（或贵）可以使用我们提供的 Solo 付费服务（5￥/月），详情请戳[**这里**](http://b3log.org/services)。
