### ISSUE TITLE
Solo 新版

### ISSUE THREAD

**Issue by 88250** [b3log/b3log-solo#321]
*这个 issue 已经关闭了，为了让大家了解 Solo 的去向，才再次打开的，请勿评论，谢谢！更多信息请大家移步 https://github.com/b3log/b3log-noty/issues/1*

----

彻底放弃 GAE 平台（类似有沙箱限制的平台），加强对标准 Servlet 容器环境平台的支持（例如支持文件上传： #166 ）。

* 0.6 是 Solo  的最后一个大版本（后面只会发布 0.6.x 修复缺陷）
* **Solo 项目是会一直维护的，但不再增加新特性，只进行修复缺陷**
* 会提供数据导出/导入程序，方便迁移数据到新的版本中，如果不迁移，也可以一直使用 Solo
* 新版会更加突出_标签_这个核心特性：加入知识管理与分享（参见 Tag Forge： http://symphony.b3log.org/about ）
* 新的名字大家帮忙想想，要围绕 B3log 的创意（ http://symphony.b3log.org/about ）哦，延续 Solo 精神

**Comment by stevenlii** [comment]
怎么安装啊, 有3个文件, 一个zip, 两个war包, 如何在linux下安装?

**Comment by 88250** [comment]
@stevenlii 请看这里：https://github.com/b3log/b3log-solo/wiki/deploy_local_tomcat

**Comment by stevenlii** [comment]
有没有部署好的, 我想看下效果

**Comment by 88250** [comment]
@stevenlii http://demo.b3log.org 右上角登录，
用户名：b3log.solo@gmail.com
密码：b3logsolo
